// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Praxis Contributors

//! Shared provider-hop contracts for routing filters.
//!
//! These headers are owned by Praxis AI rather than Praxis core. The edge
//! filter removes client-supplied values before setting replacements, and a
//! provider gateway consumes them only after authenticating and authorizing
//! the mTLS peer.

/// Selected-candidate header forwarded from the edge gateway.
pub(crate) const SELECTED_CANDIDATE_HEADER: &str = "x-ai-routing-candidate";

/// Per-hop request identifier generated by the edge gateway.
pub(crate) const PROVIDER_HOP_REQUEST_ID_HEADER: &str = "x-ai-routing-request-id";

/// Serving overlay revision forwarded from the edge gateway.
pub(crate) const OVERLAY_REVISION_HEADER: &str = "x-ai-routing-revision";

/// Admission state of the selected route candidate.
pub(crate) const ROUTE_ADMISSION_STATE: &str = "intelligent_route.admission_state";

/// Backend cluster selected by `intelligent_route`.
pub(crate) const ROUTE_CLUSTER: &str = "intelligent_route.cluster";

/// Candidate kind.
pub(crate) const ROUTE_KIND: &str = "intelligent_route.kind";

/// Local site name of the routing gateway.
pub(crate) const ROUTE_LOCAL_SITE: &str = "intelligent_route.local_site";

/// Candidate name from the overlay.
pub(crate) const ROUTE_NAME: &str = "intelligent_route.name";

/// Provider-hop request ID generated by the edge gateway.
pub(crate) const ROUTE_PROVIDER_HOP_REQUEST_ID: &str = "intelligent_route.provider_hop_request_id";

/// Selection rank within the candidate tier.
pub(crate) const ROUTE_RANK: &str = "intelligent_route.rank";

/// Selection tier.
pub(crate) const ROUTE_SELECTION_TIER: &str = "intelligent_route.selection_tier";

/// Remote site name of the selected candidate.
pub(crate) const ROUTE_SITE: &str = "intelligent_route.site";

/// Stable identifier for the selected candidate.
pub(crate) const ROUTE_STABLE_ID: &str = "intelligent_route.stable_id";

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn peer_context_headers_are_not_praxis_reserved() {
        for header in [
            SELECTED_CANDIDATE_HEADER,
            PROVIDER_HOP_REQUEST_ID_HEADER,
            OVERLAY_REVISION_HEADER,
        ] {
            assert!(
                !praxis_core::reserved_headers::is_reserved(header),
                "{header} would be stripped by the Praxis upstream boundary"
            );
        }
    }

    #[test]
    fn peer_context_uses_fixed_ai_routing_namespace() {
        for header in [
            SELECTED_CANDIDATE_HEADER,
            PROVIDER_HOP_REQUEST_ID_HEADER,
            OVERLAY_REVISION_HEADER,
        ] {
            assert!(
                header.starts_with("x-ai-routing-"),
                "{header} must remain in the AI routing namespace"
            );
        }
    }
}
