// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Praxis Contributors

//! Shared request-context and metadata contracts for routing filters.
//!
//! The HTTP headers in this module are AI-owned hop contracts. They deliberately
//! do not use Praxis-reserved `x-praxis-*` names because Praxis strips that
//! namespace before every upstream hop. The owning filter must remove
//! client-supplied values before setting replacements. Provider gateways consume
//! peer fields only after mTLS peer authentication and authorization.

use praxis_filter::HttpFilterContext;
use serde::Deserialize;

/// Selected-candidate header forwarded from the edge gateway.
pub(crate) const SELECTED_CANDIDATE_HEADER: &str = "x-ai-routing-candidate";

/// Per-hop request identifier generated by the edge gateway.
pub(crate) const PROVIDER_HOP_REQUEST_ID_HEADER: &str = "x-ai-routing-request-id";

/// Serving overlay revision forwarded from the edge gateway.
pub(crate) const OVERLAY_REVISION_HEADER: &str = "x-ai-routing-revision";

/// Provider identity header added only for backend/demo capture.
pub(crate) const PROVIDER_ATTRIBUTION_HEADER: &str = "x-ai-provider-attribution";

/// Correlation header overwritten by the provider gateway for backend capture.
pub(crate) const PROVIDER_REQUEST_ID_HEADER: &str = "x-ai-provider-request-id";

/// Provider-owned copy of the serving overlay revision for backend telemetry.
pub(crate) const PROVIDER_OVERLAY_REVISION_HEADER: &str = "x-ai-provider-routing-revision";

/// Demo-only response attribution header.
pub(crate) const PROVIDER_ATTRIBUTION_RESPONSE_HEADER: &str = "x-ai-demo-provider-gateway";

/// Admission state of the selected route candidate.
pub(crate) const ROUTE_ADMISSION_STATE: &str = "intelligent_route.admission_state";
/// Backend cluster selected by `intelligent_route`.
pub(crate) const ROUTE_CLUSTER: &str = "intelligent_route.cluster";
/// Candidate kind (e.g. `inference_model`, `mcp_tool`).
pub(crate) const ROUTE_KIND: &str = "intelligent_route.kind";
/// Local site name of the routing gateway.
pub(crate) const ROUTE_LOCAL_SITE: &str = "intelligent_route.local_site";
/// Candidate name from the overlay.
pub(crate) const ROUTE_NAME: &str = "intelligent_route.name";
/// Selection rank within the candidate tier.
pub(crate) const ROUTE_RANK: &str = "intelligent_route.rank";
/// Selection tier (primary, fallback, etc.).
pub(crate) const ROUTE_SELECTION_TIER: &str = "intelligent_route.selection_tier";
/// Remote site name of the selected candidate.
pub(crate) const ROUTE_SITE: &str = "intelligent_route.site";
/// Stable identifier for the selected candidate.
pub(crate) const ROUTE_STABLE_ID: &str = "intelligent_route.stable_id";
/// Hop request ID forwarded to the provider gateway.
pub(crate) const ROUTE_PROVIDER_HOP_REQUEST_ID: &str = "intelligent_route.provider_hop_request_id";

/// Candidate ID validated by `provider_route`.
pub(crate) const PROVIDER_ROUTE_CANDIDATE_ID: &str = "provider_route.candidate_id";
/// Provider-local backend cluster.
pub(crate) const PROVIDER_ROUTE_CLUSTER: &str = "provider_route.cluster";
/// Model validated by `provider_route`.
pub(crate) const PROVIDER_ROUTE_MODEL: &str = "provider_route.model";
/// Provider identity for attribution.
pub(crate) const PROVIDER_ROUTE_PROVIDER_ID: &str = "provider_route.provider_id";
/// Provider-scoped request ID.
pub(crate) const PROVIDER_ROUTE_REQUEST_ID: &str = "provider_route.request_id";
/// Serving overlay revision validated by `provider_route`.
pub(crate) const PROVIDER_ROUTE_OVERLAY_REVISION: &str = "provider_route.overlay_revision";

/// Credential injection strategy (e.g. `bearer_token`).
pub(crate) const CREDENTIAL_STRATEGY: &str = "intelligent_route.credential.strategy";
/// Secret name for credential lookup.
pub(crate) const CREDENTIAL_NAME: &str = "intelligent_route.credential.name";
/// Secret namespace for credential lookup.
pub(crate) const CREDENTIAL_NAMESPACE: &str = "intelligent_route.credential.namespace";
/// Secret data key for credential lookup.
pub(crate) const CREDENTIAL_KEY: &str = "intelligent_route.credential.key";

/// Bearer token injection strategy identifier.
pub(crate) const STRATEGY_BEARER_TOKEN: &str = "bearer_token";

/// Kubernetes Secret reference. Only locator fields are carried in routing
/// configuration and request metadata.
#[derive(Clone, Debug, Deserialize, Eq, Hash, PartialEq)]
#[serde(deny_unknown_fields)]
pub(crate) struct CredentialRef {
    /// Secret data key.
    pub key: String,
    /// Secret name.
    pub name: String,
    /// Secret namespace.
    pub namespace: String,
}

/// Provider-local reference to credential bytes resolved by
/// `credential_inject`.
#[derive(Clone, Debug, Deserialize, Eq, Hash, PartialEq)]
#[serde(deny_unknown_fields, rename_all = "camelCase")]
pub(crate) struct CandidateCredential {
    /// Injection strategy.
    pub strategy: String,

    /// Secret locator, never secret bytes.
    pub secret_ref: CredentialRef,
}

/// Replace credential-reference metadata with provider-local policy output.
pub(crate) fn set_credential_metadata(ctx: &mut HttpFilterContext<'_>, credential: Option<&CandidateCredential>) {
    clear_credential_metadata(ctx);
    let Some(credential) = credential else {
        return;
    };
    ctx.set_metadata(CREDENTIAL_STRATEGY, &credential.strategy);
    ctx.set_metadata(CREDENTIAL_NAME, &credential.secret_ref.name);
    ctx.set_metadata(CREDENTIAL_NAMESPACE, &credential.secret_ref.namespace);
    ctx.set_metadata(CREDENTIAL_KEY, &credential.secret_ref.key);
}

/// Remove any previously written credential-reference metadata.
pub(crate) fn clear_credential_metadata(ctx: &mut HttpFilterContext<'_>) {
    ctx.filter_metadata.remove(CREDENTIAL_STRATEGY);
    ctx.filter_metadata.remove(CREDENTIAL_NAME);
    ctx.filter_metadata.remove(CREDENTIAL_NAMESPACE);
    ctx.filter_metadata.remove(CREDENTIAL_KEY);
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn forwarded_routing_headers_are_not_praxis_reserved() {
        for header in [
            SELECTED_CANDIDATE_HEADER,
            PROVIDER_HOP_REQUEST_ID_HEADER,
            OVERLAY_REVISION_HEADER,
            PROVIDER_ATTRIBUTION_HEADER,
            PROVIDER_OVERLAY_REVISION_HEADER,
            PROVIDER_REQUEST_ID_HEADER,
        ] {
            assert!(
                !praxis_core::reserved_headers::is_reserved(header),
                "{header} would be stripped by the Praxis upstream boundary"
            );
        }
    }

    #[test]
    fn peer_context_uses_fixed_routing_namespace() {
        for header in [
            SELECTED_CANDIDATE_HEADER,
            PROVIDER_HOP_REQUEST_ID_HEADER,
            OVERLAY_REVISION_HEADER,
        ] {
            assert!(
                header.starts_with("x-ai-routing-"),
                "{header} must remain in the AI routing namespace"
            );
        }
    }
}
