// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2026 Praxis Contributors

//! Owned operation contracts and implementation `OpenAPI` generation.
//!
//! Split from the runtime operation metadata so builds that only classify
//! operations do not compile `utoipa`.

use std::borrow::{Borrow, Cow};

use utoipa::openapi::{
    Components, Content, Info, OpenApi, Paths, Ref, RefOr, Required, Tag,
    path::{HttpMethod as OpenApiHttpMethod, Operation, OperationBuilder, Parameter, ParameterBuilder, ParameterIn},
    request_body::RequestBodyBuilder,
    response::ResponseBuilder,
    schema::Schema,
};

use super::OpenAiOperationSpec;
use crate::operation::HttpMethod;

/// Component schemas recursively referenced by one contract type.
type ReferencedSchemas = Vec<(String, RefOr<Schema>)>;

/// Type-erased access to one concrete `ToSchema` implementation.
#[derive(Clone, Copy)]
pub(crate) struct SchemaBinding {
    /// Return the component name.
    name: fn() -> Cow<'static, str>,
    /// Generate the component schema.
    schema: fn() -> RefOr<Schema>,
    /// Collect recursively referenced schemas.
    referenced_schemas: fn(&mut ReferencedSchemas),
}

impl SchemaBinding {
    /// Bind one concrete Rust schema type.
    pub(crate) const fn new(
        name: fn() -> Cow<'static, str>,
        schema: fn() -> RefOr<Schema>,
        referenced_schemas: fn(&mut ReferencedSchemas),
    ) -> Self {
        Self {
            name,
            schema,
            referenced_schemas,
        }
    }

    /// Component name generated by the bound Rust type.
    fn name(self) -> Cow<'static, str> {
        (self.name)()
    }

    /// Schema generated by the bound Rust type.
    fn schema(self) -> RefOr<Schema> {
        (self.schema)()
    }

    /// Collect schemas referenced by the bound Rust type.
    fn collect_referenced(self, schemas: &mut ReferencedSchemas) {
        (self.referenced_schemas)(schemas);
    }
}

/// Bind a concrete Rust contract type to its generated component schema.
macro_rules! schema_binding {
    ($schema:ty) => {
        $crate::openai::operation::SchemaBinding::new(
            <$schema as utoipa::ToSchema>::name,
            <$schema as utoipa::PartialSchema>::schema,
            <$schema as utoipa::ToSchema>::schemas,
        )
    };
}

pub(crate) use schema_binding;

/// Location of one operation parameter.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) enum ParameterLocation {
    /// Parameter embedded in the request path.
    Path,
    /// Parameter read from the query string.
    Query,
}

/// `OpenAPI` metadata for one operation parameter.
#[derive(Clone, Copy)]
pub(crate) struct ParameterSpec {
    /// Parameter name.
    pub(crate) name: &'static str,
    /// Parameter location.
    pub(crate) location: ParameterLocation,
    /// Whether the parameter is required.
    pub(crate) required: bool,
    /// Human-readable parameter description.
    pub(crate) description: &'static str,
    /// Generate the inline parameter schema.
    schema: fn() -> RefOr<Schema>,
}

impl ParameterSpec {
    /// Declare one parameter backed by a concrete Rust schema type.
    pub(crate) const fn new(
        name: &'static str,
        location: ParameterLocation,
        required: bool,
        description: &'static str,
        schema: fn() -> RefOr<Schema>,
    ) -> Self {
        Self {
            name,
            location,
            required,
            description,
            schema,
        }
    }

    /// Generate the inline parameter schema.
    fn schema(self) -> RefOr<Schema> {
        (self.schema)()
    }
}

/// One media type and schema owned by an operation.
#[derive(Clone, Copy)]
pub(crate) struct MediaTypeSpec {
    /// HTTP media type, such as `application/json` or `multipart/form-data`.
    pub(crate) content_type: &'static str,
    /// Schema associated with this representation.
    pub(crate) schema: SchemaBinding,
}

impl MediaTypeSpec {
    /// Declare one schema-backed media type.
    pub(crate) const fn new(content_type: &'static str, schema: SchemaBinding) -> Self {
        Self { content_type, schema }
    }
}

/// Request body contract owned by an operation.
#[derive(Clone, Copy)]
pub(crate) struct RequestBodySpec {
    /// Whether the body is required.
    pub(crate) required: bool,
    /// Accepted media representations.
    pub(crate) content: &'static [MediaTypeSpec],
}

/// One response contract owned by an operation.
#[derive(Clone, Copy)]
pub(crate) struct ResponseSpec {
    /// HTTP response status code.
    pub(crate) status: &'static str,
    /// Human-readable response description.
    pub(crate) description: &'static str,
    /// Response media representations. Empty for bodyless responses.
    pub(crate) content: &'static [MediaTypeSpec],
}

/// `OpenAPI` contract owned by one local or transforming operation.
#[derive(Clone, Copy)]
pub(crate) struct OwnedOperationContract {
    /// Operation parameters.
    pub(crate) parameters: &'static [ParameterSpec],
    /// Request body, when present.
    pub(crate) request: Option<RequestBodySpec>,
    /// Responses produced by the operation.
    pub(crate) responses: &'static [ResponseSpec],
}

/// Convert a runtime method into Utoipa's `OpenAPI` representation.
///
/// The runtime enum is provider-neutral and carries no `OpenAPI` dependency, so
/// the mapping lives here with the generator that needs it.
const fn openapi_method(method: HttpMethod) -> OpenApiHttpMethod {
    match method {
        HttpMethod::Get => OpenApiHttpMethod::Get,
        HttpMethod::Post => OpenApiHttpMethod::Post,
        HttpMethod::Put => OpenApiHttpMethod::Put,
        HttpMethod::Delete => OpenApiHttpMethod::Delete,
        HttpMethod::Patch => OpenApiHttpMethod::Patch,
        HttpMethod::Head => OpenApiHttpMethod::Head,
        HttpMethod::Options => OpenApiHttpMethod::Options,
        HttpMethod::Trace => OpenApiHttpMethod::Trace,
    }
}

/// Generate an implementation `OpenAPI` document from runtime operation specs.
pub(crate) fn implementation_openapi<I>(title: &str, version: &str, tag: &str, specs: I) -> OpenApi
where
    I: IntoIterator,
    I::Item: Borrow<OpenAiOperationSpec>,
{
    let mut openapi = OpenApi::new(Info::new(title, version), Paths::new());
    openapi.tags = Some(vec![Tag::new(tag)]);
    let mut components = Components::new();

    for spec in specs {
        let spec = spec.borrow();
        let Some(contract) = spec.owned_contract() else {
            continue;
        };
        if !spec.owns_contract() {
            continue;
        }

        register_contract_schemas(&mut components, contract);
        openapi.paths.add_path_operation(
            spec.spec_path,
            vec![openapi_method(spec.method())],
            build_operation(spec, contract, tag),
        );
    }

    openapi.components = Some(components);
    openapi
}

/// Register all concrete schemas referenced by one operation contract.
fn register_contract_schemas(components: &mut Components, contract: OwnedOperationContract) {
    if let Some(request) = contract.request {
        for media in request.content {
            register_schema(components, media.schema);
        }
    }
    for response in contract.responses {
        for media in response.content {
            register_schema(components, media.schema);
        }
    }
}

/// Register a concrete schema and all schemas referenced by it.
fn register_schema(components: &mut Components, binding: SchemaBinding) {
    let mut referenced = Vec::new();
    binding.collect_referenced(&mut referenced);
    components.schemas.extend(referenced);
    components.schemas.insert(binding.name().into_owned(), binding.schema());
}

/// Build one `OpenAPI` operation from its registry metadata.
fn build_operation(spec: &OpenAiOperationSpec, contract: OwnedOperationContract, tag: &str) -> Operation {
    let mut operation = OperationBuilder::new().operation_id(Some(spec.operation_id())).tag(tag);

    for response in contract.responses {
        let mut builder = ResponseBuilder::new().description(response.description);
        for media in response.content {
            builder = builder.content(media.content_type, schema_content(media.schema));
        }
        operation = operation.response(response.status, builder.build());
    }

    if !contract.parameters.is_empty() {
        operation = operation.parameters(Some(contract.parameters.iter().copied().map(build_parameter)));
    }

    if let Some(request) = contract.request {
        let mut builder = RequestBodyBuilder::new().required(Some(required(request.required)));
        for media in request.content {
            builder = builder.content(media.content_type, schema_content(media.schema));
        }
        operation = operation.request_body(Some(builder.build()));
    }

    operation.build()
}

/// Build one path or query parameter.
fn build_parameter(spec: ParameterSpec) -> Parameter {
    ParameterBuilder::new()
        .name(spec.name)
        .parameter_in(match spec.location {
            ParameterLocation::Path => ParameterIn::Path,
            ParameterLocation::Query => ParameterIn::Query,
        })
        .description(Some(spec.description))
        .required(required(spec.required))
        .schema(Some(spec.schema()))
        .build()
}

/// Build media content referencing one registered component schema.
fn schema_content(binding: SchemaBinding) -> Content {
    Content::new(Some(Ref::from_schema_name(binding.name().into_owned())))
}

/// Convert a boolean required flag into Utoipa's representation.
const fn required(value: bool) -> Required {
    if value { Required::True } else { Required::False }
}

#[cfg(test)]
#[expect(clippy::allow_attributes, reason = "blanket test suppressions")]
#[allow(clippy::unwrap_used, reason = "tests")]
mod tests {
    use serde_json::Value as JsonValue;
    use utoipa::ToSchema;

    use super::*;
    use crate::operation::{ApplicationProtocol, HandlingMode, OperationSpec, RequestBody, Transport};

    /// Files protocol identifier, for these tests only.
    const OPENAI_FILES: ApplicationProtocol = ApplicationProtocol::new("openai_files");

    /// Representative multipart upload form.
    #[derive(ToSchema)]
    #[expect(dead_code, reason = "schema-only test contract")]
    struct UploadForm {
        /// Upload purpose.
        purpose: String,
    }

    /// Representative JSON response.
    #[derive(ToSchema)]
    #[expect(dead_code, reason = "schema-only test contract")]
    struct FileResource {
        /// File identifier.
        id: String,
    }

    /// Files-like operation exercising non-JSON and multiple response shapes.
    const FILE_OPERATION: OpenAiOperationSpec = OpenAiOperationSpec {
        runtime: OperationSpec {
            application_protocol: OPENAI_FILES,
            operation_id: "createFile",
            method: HttpMethod::Post,
            transport: Transport::Http,
            runtime_path: "/v1/files",
            mode: HandlingMode::Local,
            request_body: RequestBody::Multipart { required: true },
        },
        spec_path: "/files",
        owned_contract: Some(OwnedOperationContract {
            parameters: &[],
            request: Some(RequestBodySpec {
                required: true,
                content: &[MediaTypeSpec::new("multipart/form-data", schema_binding!(UploadForm))],
            }),
            responses: &[
                ResponseSpec {
                    status: "200",
                    description: "OK",
                    content: &[MediaTypeSpec::new("application/json", schema_binding!(FileResource))],
                },
                ResponseSpec {
                    status: "204",
                    description: "No content",
                    content: &[],
                },
            ],
        }),
    };

    /// Proxied upload: a real multipart body with no Praxis-owned contract.
    const PROXIED_UPLOAD: OpenAiOperationSpec = OpenAiOperationSpec {
        runtime: OperationSpec {
            application_protocol: OPENAI_FILES,
            operation_id: "createUpload",
            method: HttpMethod::Post,
            transport: Transport::Http,
            runtime_path: "/v1/uploads",
            mode: HandlingMode::Passthrough,
            request_body: RequestBody::Multipart { required: true },
        },
        spec_path: "/uploads",
        owned_contract: None,
    };

    /// Proxied bodyless read.
    const PROXIED_GET: OpenAiOperationSpec = OpenAiOperationSpec {
        runtime: OperationSpec {
            application_protocol: OPENAI_FILES,
            operation_id: "getUpload",
            method: HttpMethod::Get,
            transport: Transport::Http,
            runtime_path: "/v1/uploads/{upload_id}",
            mode: HandlingMode::Passthrough,
            request_body: RequestBody::None,
        },
        spec_path: "/uploads/{upload_id}",
        owned_contract: None,
    };

    #[test]
    fn request_body_shape_is_independent_of_contract_ownership() {
        assert!(!PROXIED_UPLOAD.owns_contract());
        assert!(PROXIED_UPLOAD.owned_contract().is_none());
        assert!(
            PROXIED_UPLOAD.has_request_body(),
            "a proxied multipart upload must report its body without owning a contract"
        );
        assert!(PROXIED_UPLOAD.request_body().is_required());
        assert_eq!(PROXIED_UPLOAD.request_body().as_str(), "multipart");

        assert!(!PROXIED_GET.has_request_body());
        assert!(!PROXIED_GET.request_body().is_required());
    }

    #[test]
    fn optional_body_is_present_but_not_required() {
        let body = RequestBody::Json { required: false };
        assert!(body.is_present());
        assert!(!body.is_required());
        assert_eq!(body.as_str(), "json");
    }

    #[test]
    fn owned_contract_operations_still_report_their_body() {
        assert!(FILE_OPERATION.has_request_body());
        assert!(FILE_OPERATION.owned_contract().is_some());
    }

    #[test]
    fn generated_contract_supports_files_style_media_and_responses() {
        let document = implementation_openapi("Files test", "0.1.0", "Files", std::iter::once(&FILE_OPERATION));
        let value = serde_json::to_value(document).unwrap();

        assert_eq!(
            value.pointer("/paths/~1files/post/requestBody/required"),
            Some(&JsonValue::Bool(true))
        );
        assert!(
            value
                .pointer("/paths/~1files/post/requestBody/content/multipart~1form-data/schema/$ref")
                .is_some()
        );
        assert!(
            value
                .pointer("/paths/~1files/post/responses/200/content/application~1json/schema/$ref")
                .is_some()
        );
        assert!(value.pointer("/paths/~1files/post/responses/204/content").is_none());
    }
}
