// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2026 Praxis Contributors

//! `cargo xtask sync-inference-readme` keeps the inference fixture coverage
//! inventory synchronized with its versioned manifest.

use std::{
    collections::BTreeSet,
    fmt::Write as _,
    fs,
    path::{Path, PathBuf},
};

use clap::Parser;
use praxis_test_utils::inference_fixture::{CoverageFeature, CoverageManifest, CoverageStatus};

/// Marker beginning the generated inference coverage block.
const GENERATED_START: &str = "<!-- BEGIN GENERATED INFERENCE COVERAGE -->";

/// Marker ending the generated inference coverage block.
const GENERATED_END: &str = "<!-- END GENERATED INFERENCE COVERAGE -->";

/// Default inference fixture directory relative to the workspace root.
const FIXTURE_ROOT: &str = "tests/integration/fixtures/inference";

/// CLI arguments for `cargo xtask sync-inference-readme`.
#[derive(Parser)]
pub(crate) struct Args {
    /// Write the generated coverage block instead of checking for drift.
    #[arg(long)]
    fix: bool,
}

/// Result of synchronizing the generated README block.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
enum SyncOutcome {
    /// The current block already matches the coverage manifest.
    UpToDate,
    /// Fix mode replaced a stale generated block.
    Updated,
}

/// Verify or regenerate the inference fixture coverage inventory.
pub(crate) fn run(args: &Args) {
    let fixture_root = workspace_root().join(FIXTURE_ROOT);
    let readme_path = fixture_root.join("README.md");
    match sync_paths(&fixture_root, &readme_path, args.fix) {
        Ok(SyncOutcome::UpToDate) => println!("inference fixture README coverage is up to date"),
        Ok(SyncOutcome::Updated) => println!("wrote {}", readme_path.display()),
        Err(error) => {
            eprintln!("{error}");
            if !args.fix && error == "inference fixture README coverage is out of date" {
                eprintln!("run `cargo xtask sync-inference-readme --fix` to regenerate");
            }
            std::process::exit(1);
        },
    }
}

/// Synchronize explicit fixture and README paths for command and unit tests.
fn sync_paths(fixture_root: &Path, readme_path: &Path, fix: bool) -> Result<SyncOutcome, String> {
    let manifest = CoverageManifest::load(&fixture_root.join("coverage.yaml"))
        .map_err(|error| format!("inference coverage manifest could not be loaded: {error}"))?;
    let current = fs::read_to_string(readme_path)
        .map_err(|error| format!("inference fixture README could not be read: {error}"))?;
    let generated = render_generated_block(&manifest);
    let updated = replace_generated_block(&current, &generated)?;

    if current == updated {
        return Ok(SyncOutcome::UpToDate);
    }
    if !fix {
        return Err("inference fixture README coverage is out of date".to_owned());
    }

    fs::write(readme_path, updated)
        .map_err(|error| format!("inference fixture README could not be written: {error}"))?;
    Ok(SyncOutcome::Updated)
}

/// Render the complete generated block from manifest declarations.
fn render_generated_block(manifest: &CoverageManifest) -> String {
    let scenarios = manifest
        .features
        .iter()
        .flat_map(|feature| feature.scenarios.iter().map(String::as_str))
        .collect::<BTreeSet<_>>();
    let mut output = String::new();
    output.push_str(GENERATED_START);
    output.push('\n');
    output.push_str("<!-- Generated by `cargo xtask sync-inference-readme`; do not edit. -->\n\n");
    _ = writeln!(
        output,
        "The manifest declares **{} {}** across **{} {}**, linked to **{} {}**.",
        manifest.features.len(),
        plural(manifest.features.len(), "feature", "features"),
        manifest.scope.len(),
        plural(manifest.scope.len(), "scope", "scopes"),
        scenarios.len(),
        plural(scenarios.len(), "scenario", "scenarios")
    );
    output.push_str("\n| Scope | Feature | Status | Scenarios | Provider coverage |\n");
    output.push_str("| --- | --- | --- | --- | --- |\n");
    for feature in &manifest.features {
        output.push_str(&render_feature_row(feature));
        output.push('\n');
    }
    output.push_str(GENERATED_END);
    output
}

/// Render one feature row in manifest order.
fn render_feature_row(feature: &CoverageFeature) -> String {
    format!(
        "| {} | {} | {} | {} | {} |",
        render_code_list(&feature.scopes),
        render_code(&feature.id),
        render_code(coverage_status_name(&feature.status)),
        render_code_list(&feature.scenarios),
        render_provider_coverage(feature)
    )
}

/// Render provider requirements in deterministic map order.
fn render_provider_coverage(feature: &CoverageFeature) -> String {
    if feature.providers.is_empty() {
        return "—".to_owned();
    }
    feature
        .providers
        .iter()
        .map(|(provider, coverage)| {
            format!(
                "{}: {}",
                render_code(provider),
                render_code(coverage_status_name(&coverage.status))
            )
        })
        .collect::<Vec<_>>()
        .join("<br>")
}

/// Replace exactly one generated coverage block while preserving other prose.
fn replace_generated_block(current: &str, generated: &str) -> Result<String, String> {
    let start_count = current.matches(GENERATED_START).count();
    let end_count = current.matches(GENERATED_END).count();
    if start_count == 0 || end_count == 0 {
        return Err("inference README generated coverage markers are missing".to_owned());
    }
    if start_count != 1 || end_count != 1 {
        return Err("inference README generated coverage markers are duplicated".to_owned());
    }

    let start = current
        .find(GENERATED_START)
        .ok_or_else(|| "inference README generated coverage markers are missing".to_owned())?;
    let end_start = current
        .find(GENERATED_END)
        .ok_or_else(|| "inference README generated coverage markers are missing".to_owned())?;
    if end_start < start {
        return Err("inference README generated coverage markers are out of order".to_owned());
    }
    let end = end_start + GENERATED_END.len();
    let before = current
        .get(..start)
        .ok_or_else(|| "inference README generated coverage markers are invalid".to_owned())?;
    let after = current
        .get(end..)
        .ok_or_else(|| "inference README generated coverage markers are invalid".to_owned())?;
    Ok(format!("{before}{generated}{after}"))
}

/// Render one manifest identifier as safe inline Markdown code.
fn render_code(value: &str) -> String {
    let value = value
        .replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('|', "&#124;")
        .replace('`', "&#96;")
        .replace(['\r', '\n'], " ");
    format!("`{value}`")
}

/// Render a line-broken list of manifest identifiers.
fn render_code_list(values: &[String]) -> String {
    values
        .iter()
        .map(|value| render_code(value))
        .collect::<Vec<_>>()
        .join("<br>")
}

/// Stable serialized spelling of a coverage status.
const fn coverage_status_name(status: &CoverageStatus) -> &'static str {
    match status {
        CoverageStatus::Covered => "covered",
        CoverageStatus::LiveCovered => "live_covered",
        CoverageStatus::SyntheticOnly => "synthetic_only",
        CoverageStatus::Unsupported => "unsupported",
        CoverageStatus::ProviderUnsupported => "provider_unsupported",
    }
}

/// Choose the singular or plural label for an aggregate count.
const fn plural<'a>(count: usize, singular: &'a str, plural: &'a str) -> &'a str {
    if count == 1 { singular } else { plural }
}

/// Locate the workspace root from the xtask manifest directory.
fn workspace_root() -> PathBuf {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set — run via `cargo xtask`");
    Path::new(&manifest_dir)
        .parent()
        .unwrap_or_else(|| Path::new("."))
        .to_owned()
}

#[cfg(test)]
mod tests {
    use std::fs;

    use praxis_test_utils::inference_fixture::CoverageManifest;

    use super::*;

    const MANIFEST: &str = "
version: 1
scope:
  - messages_to_chat
  - messages_native
features:
  - id: messages.request.minimal
    scopes:
      - messages_to_chat
    status: live_covered
    scenarios:
      - messages/basic
      - messages/stream
    providers:
      vllm:
        status: live_covered
      openai:
        status: covered
  - id: messages.native.tool_use
    scopes:
      - messages_native
    status: synthetic_only
    scenarios:
      - messages/tool
    providers:
      synthetic:
        status: synthetic_only
";

    fn manifest() -> CoverageManifest {
        serde_yaml::from_str(MANIFEST).expect("test coverage manifest must parse")
    }

    fn readme_with(body: &str) -> String {
        format!("# Fixture guide\n\n{GENERATED_START}\n{body}\n{GENERATED_END}\n\n## Workflow\n")
    }

    #[test]
    fn renderer_lists_manifest_features_scenarios_and_sorted_providers() {
        let rendered = render_generated_block(&manifest());

        assert_eq!(
            rendered,
            "<!-- BEGIN GENERATED INFERENCE COVERAGE -->\n\
<!-- Generated by `cargo xtask sync-inference-readme`; do not edit. -->\n\
\n\
The manifest declares **2 features** across **2 scopes**, linked to **3 scenarios**.\n\
\n\
| Scope | Feature | Status | Scenarios | Provider coverage |\n\
| --- | --- | --- | --- | --- |\n\
| `messages_to_chat` | `messages.request.minimal` | `live_covered` | `messages/basic`<br>`messages/stream` | `openai`: `covered`<br>`vllm`: `live_covered` |\n\
| `messages_native` | `messages.native.tool_use` | `synthetic_only` | `messages/tool` | `synthetic`: `synthetic_only` |\n\
<!-- END GENERATED INFERENCE COVERAGE -->"
        );
    }

    #[test]
    fn replacement_preserves_hand_written_sections() {
        let current = readme_with("old table");
        let generated = render_generated_block(&manifest());

        let updated = replace_generated_block(&current, &generated).expect("markers must be replaced");

        assert!(updated.starts_with("# Fixture guide\n\n"));
        assert!(updated.ends_with("\n\n## Workflow\n"));
        assert!(updated.contains("messages.native.tool_use"));
        assert!(!updated.contains("old table"));
    }

    #[test]
    fn replacement_rejects_missing_or_duplicate_markers() {
        let generated = render_generated_block(&manifest());
        let missing_end = format!("# Guide\n{GENERATED_START}\n");
        let duplicate_start = format!("{GENERATED_START}\n{GENERATED_START}\n{GENERATED_END}\n");

        assert_eq!(
            replace_generated_block("# Guide\n", &generated).unwrap_err(),
            "inference README generated coverage markers are missing"
        );
        assert_eq!(
            replace_generated_block(&missing_end, &generated).unwrap_err(),
            "inference README generated coverage markers are missing"
        );
        assert_eq!(
            replace_generated_block(&duplicate_start, &generated).unwrap_err(),
            "inference README generated coverage markers are duplicated"
        );
    }

    #[test]
    fn sync_detects_drift_then_fix_writes_stable_readme() {
        let root = tempfile::tempdir().expect("temporary directory must be created");
        let fixture_root = root.path().join("fixtures");
        fs::create_dir_all(&fixture_root).expect("fixture root must be created");
        fs::write(fixture_root.join("coverage.yaml"), MANIFEST).expect("manifest must be written");
        let readme_path = fixture_root.join("README.md");
        fs::write(&readme_path, readme_with("stale")).expect("README must be written");

        let drift = sync_paths(&fixture_root, &readme_path, false).expect_err("stale README must fail check mode");
        assert_eq!(drift, "inference fixture README coverage is out of date");

        let outcome = sync_paths(&fixture_root, &readme_path, true).expect("fix mode must update the README");
        assert_eq!(outcome, SyncOutcome::Updated);
        let updated = fs::read_to_string(&readme_path).expect("updated README must be readable");
        assert!(updated.contains("messages.request.minimal"));

        let outcome = sync_paths(&fixture_root, &readme_path, false).expect("updated README must pass check mode");
        assert_eq!(outcome, SyncOutcome::UpToDate);
    }
}
